Added tests for nested tuples, named tuples, type aliases
Shard-Labs/starknet-hardhat-example pull request #67
Opened 2022-06-24 08:41 UTC by epShardlabs

Added tests for named tuples, type aliases and nested tuples

2022-06-24 09:41 UTC, FabijanC requested changes

2022-06-24 15:30 UTC, FabijanC commented
@PacoEdwin Also, add a few `should fail` tests (styled after the ones already in the file).

2022-06-27 05:26 UTC, taco-paco commented on test/function-args-test.ts
> +    expect(res.a).to.equal(1n);
Done

2022-06-27 10:59 UTC, FabijanC approved these changes

2022-06-27 11:02 UTC, merged